import "./globals.css";
import Navigation from "./components/Navigation";

export const metadata = {
  title: "We are trash",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Navigation />
        <main className="flex h-full w-full justify-center mb-[80px]">
          {children}
        </main>
      </body>
    </html>
  );
}
